# Generated by Django 5.2.2 on 2025-06-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('from_reserve', models.CharField(null=True)),
                ('to_reserve', models.CharField(null=True)),
                ('duree', models.CharField(null=True)),
                ('num_salle', models.CharField()),
                ('equipements', models.JSONField()),
                ('servises', models.JSONField()),
                ('type', models.CharField()),
                ('qr_code', models.CharField()),
                ('prix', models.CharField()),
                ('status', models.CharField()),
            ],
        ),
    ]
