# Generated by Django 5.2.2 on 2025-06-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
    ]
