# Generated by Django 5.2.2 on 2025-06-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20250626_2045'),
    ]

    operations = [
    ]
