# Generated by Django 5.2.2 on 2025-07-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_duree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='piament',
            field=models.CharField(null=True),
        ),
    ]
