# Generated by Django 5.2.2 on 2025-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='equipments',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='reservation_date',
            field=models.JSONField(null=True),
        ),
    ]
