# Generated by Django 5.2.2 on 2025-07-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0002_salle_equipments_salle_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='status',
            field=models.CharField(null=True),
        ),
    ]
